### ISSUE TITLE
Use branching model

### ISSUE THREAD

**Issue by TheUltimateC0der** [damienbod/IdentityServer4AspNetCoreIdentityTemplate#13]
Maybe it would be better, to use some sort of branching model :)

**Comment by damienbod** [comment]
Hi @CUCO-Ultimate , you mean branch, PR?

Greetings Damien

**Comment by TheUltimateC0der** [comment]
I mean something like this -> https://nvie.com/posts/a-successful-git-branching-model/

**Comment by damienbod** [comment]
Ah ok, thanks. I use this for projects with large teams. At the moment, I don't think it's required here, but if the traffic, PRs was to increase, I'll switch. 

Thanks for the recommendation.
