### ISSUE TITLE
Add Spanish Localization

### ISSUE THREAD

**Issue by damienbod** [damienbod/IdentityServer4AspNetCoreIdentityTemplate#15]

**Comment by damienbod** [comment]
https://github.com/damienbod/IdentityServer4AspNetCoreIdentityTemplate/tree/master/content/StsServerIdentity/Resources

**Comment by jahbenjah** [comment]
I'm working in the spanish localization

[SharedResource.es-MX.zip](https://github.com/damienbod/IdentityServer4AspNetCoreIdentityTemplate/files/4363608/SharedResource.es-MX.zip)

**Comment by damienbod** [comment]
@jahbenjah wow thanks! 

Would you like to do a PR?, or if you want I can add it.

Greeting and thanks Damien
