### ISSUE TITLE
Add to existing Identity server projects e.g IdentityServer QuickStart based project?

### ISSUE THREAD

**Issue by asadsahi** [damienbod/IdentityServer4AspNetCoreIdentityTemplate#19]
Is it possible to add easily into an existing identity server project. e.g a project which is based on Identity server QuickStart template?

**Comment by asadsahi** [comment]
I am just upgrading one of my projects which has QuickStart ui and merging changes/additions from this project. There are some improvements in both projects. So, I'll see what I ended up with :).

**Comment by damienbod** [comment]
I'll close this, if you have any findings, improvements, or want to re-open, please

Greetings Damien
