### ISSUE TITLE
Should Logout post action be decorated with  [AllowAnonymous]?

### ISSUE THREAD

**Issue by asadsahi** [damienbod/IdentityServer4AspNetCoreIdentityTemplate#23]
In template AccountController/Logout post action is decorated with [AllowAnonymous]. Should it?

**Comment by damienbod** [comment]
Need to check this, 1 action is after the logout

**Comment by damienbod** [comment]
fixed, thanks for the issue. Included in version 1.0.8

**Comment by asadsahi** [comment]
Thanks @damienbod
