### ISSUE TITLE
_StatusMessage partial cshtml is missing

### ISSUE THREAD

**Issue by IvanFarkas** [damienbod/IdentityServer4AspNetCoreIdentityTemplate#24]
**_StatusMessage** Partial cshtml is missing

**Comment by damienbod** [comment]
@IvanFarkas Thanks for the issue. Do you what to do a PR? Otherwise I'll add it.

Greetings Damien

**Comment by damienbod** [comment]
https://github.com/damienbod/IdentityServer4AspNetCoreIdentityTemplate/blob/master/content/StsServerIdentity/Views/Manage/_StatusMessage.cshtml

This is present
