### ISSUE TITLE
Verifyemail sends resetpassword link

### ISSUE THREAD

**Issue by lsddhn** [damienbod/IdentityServer4AspNetCoreIdentityTemplate#29]
Accountcontroller.cs -> SendVerificationEmail(...)

`var callbackUrl = Url.Action("ResetPassword", "Account", new { userId = user.Id, code = code }, protocol: HttpContext.Request.Scheme);`

Should be:
`var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: HttpContext.Request.Scheme);`

**Comment by damienbod** [comment]
released v1.0.10
