### ISSUE TITLE
Translate zh-Hans

### ISSUE THREAD

**Issue by damienbod** [damienbod/IdentityServer4AspNetCoreIdentityTemplate#39]

**Comment by damienbod** [comment]
https://github.com/damienbod/IdentityServer4AspNetCoreIdentityTemplate/blob/master/content/StsServerIdentity/Resources/SharedResource.zh-Hans.resx

**Comment by damienbod** [comment]
@fanruinet Would you be interested in translating this? I found the error identity messages in your repo. Thanks. Would love to get zh-Hans support. Missing about 40 translations

A PR would be so cool

**Comment by fanruinet** [comment]
> @fanruinet Would you be interested in translating this? I found the error identity messages in your repo. Thanks. Would love to get zh-Hans support. Missing about 40 translations
> 
> A PR would be so cool

Yes, I'd love to. Is there a deadline for this translation? I'm a bit busy recently.

**Comment by damienbod** [comment]
wow, thanks, no, whenever you have time, thanks

**Comment by fanruinet** [comment]
That'd be great. I'll try to get it down by Dec 2.
