### ISSUE TITLE
Missing translations in All languages

### ISSUE THREAD

**Issue by damienbod** [damienbod/IdentityServer4AspNetCoreIdentityTemplate#46]
"Access to your applications and resources, even when you are offline"

"Invalid selection"

"Offline Access"	

"You must pick at least one permission"

"Recovery codes"

"CONSENT_CONFIRM_AUTH_REQUEST_QUOTES"  en-US =  Please confirm that the authorization request quotes the code:

"DEVICE_USER_CODE"   en-US =  User Code

"DEVICE_ENTER_CODE_DISPLAYED_ON_DEVICE"  en-US =   Please enter the code displayed on your device

"DEVICE_SUCCESS_AUTHORIZE"  en-US =  You have successfully authorized the device

"DEVICE_SUCCESS" en-US =  Success

"Your user identifier"

"User profile"

"Your user profile information (first name, last name, etc.)"

"Your email address"

**Comment by damienbod** [comment]
@Franklin89 @kasuken @fanruinet

Any chance you could add these? maybe directly in this issue, if you what to save time, or a PR, whichever is best for you.

Greetings Damien

**Comment by fanruinet** [comment]
I found duplicate string resources:
"Put these codes in a safe place."  -- Original resource key: GENERATE_2FA_RECOVERY_CODES_SAFE_PLACE

"If you lose your device and don't have the recovery codes you will lose access to your account."
 -- Original resource key: GENERATE_2FA_RECOVERY_CODES_INFO_LOSE

Can we just reuse the existing one?

**Comment by damienbod** [comment]
@fanruinet  Ah, thanks, my mistake then, I should use these instead, thanks

**Comment by damienbod** [comment]
just "Recovery codes" missing now. Thanks @fanruinet

**Comment by fanruinet** [comment]
Is "Recovery codes" still there? I didn't see it in the latest code.

**Comment by damienbod** [comment]
I just reversed the commit. It's not there now, but needs to be added.

**Comment by damienbod** [comment]
@kasuken @fanruinet any chance of doing a PR and adding the new translations? See first comment in this thread.

I added support for the Device Flow

@Franklin89 German is complete. french would be cool :)

Greetings Damien
