### ISSUE TITLE
add support for FIDO2

### ISSUE THREAD

**Issue by damienbod** [damienbod/IdentityServer4AspNetCoreIdentityTemplate#60]

**Comment by damienbod** [comment]
FIDO2_ADD_A_KEY
	Add a FIDO2 Key	

FIDO2_COULD_NOT_VERIFY_ASSERTION
	Could not verify assertion	

FIDO2_LOGIN_WITH_MFA
	Login with FIDO2 MFA	

FIDO2_MULTI_FACTOR_AUTHENTICATION
	FIDO2 Multi-factor authentication	

FIDO2_REGISTRATION_ERROR
	Could not create credentials in browser. Probably because the username is already registered with your authenticator. Please change username or authenaticator.	

FIDO2_SUPPORTED_BROWSERS
	Supported browsers	

FIDO2_TAP_YOUR_SECURITY_KEY_TO_FINISH_REGISTRATION
	Tap your security key to finish registration.	

FIDO2_TAP_YOUR_SECURITY_KEY_TO_LOGIN
	Tap your security key to login. 	

FIDO2_UNABLE_TO_LOAD_2FA_AUTHENTICATED_USER
	Unable to load two-factor authenticated user.	

FIDO2_UNKNOWN_CREDENTIALS
	Unknown credentials	

FIDO2_USER_NOTFOUND
	Unable to load user with ID '{0}'.	

FIDO2_USERNAME
	Username	

FIDO2_USERNAME_NOT_REGISTERED
	Username was not registered	

FIDO2_WEBAUTHN_NOT_SUPPORTED
	Please note: Your browser does not seem to support WebAuthn yet.

**Comment by damienbod** [comment]
@Franklin89 @kasuken @fanruinet

Any chance you could add the above localizations for the new FIDO2 feature? maybe directly in this issue, if you what to save time, or a PR, whichever is best for you.

Greetings Damien

**Comment by damienbod** [comment]
@Franklin89  Could you also validate my german translations? :)

**Comment by fanruinet** [comment]
Simplified Chinese:
FIDO2_ADD_A_KEY
新增FIDO2秘钥

FIDO2_COULD_NOT_VERIFY_ASSERTION
无法验证断言

FIDO2_LOGIN_WITH_MFA
使用FIDO2多因素认证登录

FIDO2_MULTI_FACTOR_AUTHENTICATION
FIDO2多因素认证

FIDO2_REGISTRATION_ERROR
无法在浏览器中创建凭证。可能是因为该用户名已被您的身份验证器所注册。请更换用户名或身份验证器。

FIDO2_SUPPORTED_BROWSERS
支持的浏览器

FIDO2_TAP_YOUR_SECURITY_KEY_TO_FINISH_REGISTRATION
点击您的安全密钥以完成注册。

FIDO2_TAP_YOUR_SECURITY_KEY_TO_LOGIN
点击您的安全密钥完成登录。

FIDO2_UNABLE_TO_LOAD_2FA_AUTHENTICATED_USER
无法加载双因素认证的用户。

FIDO2_UNKNOWN_CREDENTIALS
未知的凭证

FIDO2_USER_NOTFOUND
无法加载ID为'{0}'的用户。

FIDO2_USERNAME
用户名

FIDO2_USERNAME_NOT_REGISTERED
用户名没有注册

FIDO2_WEBAUTHN_NOT_SUPPORTED
请注意：您的浏览器很可能还不支持Web身份验证(WebAuthn)技术。

**Comment by damienbod** [comment]
@fanruinet added this, thank you!

**Comment by damienbod** [comment]
released 4.0.1

**Comment by damienbod** [comment]
@kasuken could you control the FIDO2 translations? Added a first version to the it-IT resx
