### ISSUE TITLE
Provide DB Dump and sample Migration Files

### ISSUE THREAD

**Issue by derbl4ck** [damienbod/IdentityServer4AspNetCoreIdentityTemplate#67]
Adding the migrations from ConfigurationDbContext and PersistedGrantDbContext for sqlServer worked smoothly. Unfortunately, I keep encountering errors when adding the ApplicationDbContext migrations. Therefore it would be extremely helpful to have a sample database dump and see for example migrations under / Data / Migrations.

**Comment by derbl4ck** [comment]
is there already a schedule when a full working example is available?

**Comment by damienbod** [comment]
@derbl4ck Microsoft SQL example?

**Comment by derbl4ck** [comment]
@damienbod Would be fine for me :)

**Comment by damienbod** [comment]
@derbl4ck 

https://github.com/damienbod/DemoTokensApiKeyVault/tree/master/StsServerIdentity/Migrations

And here's the ps scripts

```
Add-Migration "init_sts" -c ApplicationDbContext

Update-Database -c ApplicationDbContext

Add-Migration "init_id4_store" -c PersistedGrantDbContext

Update-Database -c PersistedGrantDbContext
```

Greetings Damien
