### ISSUE TITLE
Encode PasswordResetToken and EmailConfirmationToken to base64URL

### ISSUE THREAD

**Issue by skoruba** [damienbod/IdentityServer4AspNetCoreIdentityTemplate#92]
Hi @damienbod 

I've faced some issues that these codes were invalid, take a look at default MS Identity template:

https://github.com/dotnet/aspnetcore/blob/master/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/ForgotPassword.cshtml.cs#L79

https://github.com/dotnet/aspnetcore/blob/master/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/Register.cshtml.cs#L145

I use your code in my repository and I've fixed this issue in this commit: https://github.com/skoruba/IdentityServer4.Admin/commit/b92895e3ae45212365ea0206df2ecd3ed0b15ace

Thank you.

**Comment by damienbod** [comment]
Thanks @skoruba Will add this.

**Comment by damienbod** [comment]
released in 5.0.2, thanks for reporting.
